### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by rezabagheri** [yiisoft/widget#28]
### What steps will reproduce the problem?
Installation

### What do you get instead?
Problem 1
    - Can only install one of: psr/container[1.1.1, 1.0.0].
    - Can only install one of: psr/container[1.0.0, 1.1.1].
    - Can only install one of: psr/container[1.0.0, 1.1.1].
    - yiisoft/widget 3.0.x-dev requires psr/container 1.0.0 -> satisfiable by psr/container[1.0.0].
    - Installation request for yiisoft/widget ^3.0@dev -> satisfiable by yiisoft/widget[3.0.x-dev].
    - Installation request for psr/container (locked at 1.1.1) -> satisfiable by psr/container[1.1.1].

### Additional info

| Q                | A
| ---------------- | ---
| PHP version      |  7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
| Operating system | ubuntu 20.04
| Yii Version | version 2.0.41.1.

**Comment by samdark** [comment]
What command do you use?

**Comment by samdark** [comment]
Can't dig into issue without details :(
