### ISSUE TITLE
Widgets and DI question

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/widget#43]
Good day. I have are question with using widgets and dependency injection - how to set/change base options using DI? For example i want change options for all `Yiisoft\Yii\DataView\GridView` on pages. I wrote that `config/web/widgets.php`

```
<?php

declare(strict_types=1);

use Yiisoft\Yii\DataView\GridView;

return [
    GridView::class => [
        '$options' => [
            'class' => 'table-responsive'
        ],
        'tableOptions()' => [
            'class' => 'table table-sm table-striped table-hover'
        ]
    ]
];

```

If i remove **()** or **$** - i have error `metadata "***" is not allowed`, but with this it whatever not working. Thanks

**Comment by samdark** [comment]
Options are set via method, not property https://github.com/yiisoft/yii-dataview/blob/9886579061e5d3bbe1d0bf8de82079f065021f31/src/BaseListView.php#L192. So:

```php
<?php

declare(strict_types=1);

use Yiisoft\Yii\DataView\GridView;

return [
    GridView::class => [
        'options()' => [
            ['class' => 'table-responsive']
        ],
        'tableOptions()' => [
            ['class' => 'table table-sm table-striped table-hover']
        ]
    ]
];
```

**Comment by Gerych1984** [comment]
> Options are set via method, not property https://github.com/yiisoft/yii-dataview/blob/9886579061e5d3bbe1d0bf8de82079f065021f31/src/BaseListView.php#L192. So:
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> use Yiisoft\Yii\DataView\GridView;
> 
> return [
>     GridView::class => [
>         'options()' => [
>             ['class' => 'table-responsive']
>         ],
>         'tableOptions()' => [
>             ['class' => 'table table-sm table-striped table-hover']
>         ]
>     ]
> ];
> ```

I special set options as property, tableOptions as method. It both has no effect

**Comment by samdark** [comment]
1. There's no `options` property.
2. You haven't used arrays properly. Note extra `[]` in my example.
