### ISSUE TITLE
Is there a need for events?

### ISSUE THREAD

**Issue by samdark** [yiisoft/widget#5]
It could be that there are no valid use-cases for having global events in widgets. Need to check that.

**Comment by samdark** [comment]
Possible use case 1: Wrap all widgets with `<div class="widget"></div>` for styling purpose.

**Comment by samdark** [comment]
Use case 1 counter-argument: usually there's "main" tag in the widget and widget accepts options to be set for this tag. These options could be configured globally through widget factory config.

**Comment by yiiliveext** [comment]
> Possible use case 1: Wrap all widgets with `<div class="widget"></div>` for styling purpose.
"Writable events" is not a good idea. It is too hard to debug when a widget event has many handlers, which can modify the widget content.

**Comment by samdark** [comment]
https://forum.yiiframework.com/t/a-use-case-for-global-widget-events/128466

**Comment by pchapl** [comment]
I would suggest not to refuse at all, but not to impose events. Just provide the possibility of extension:
```php
abstract class Widget
{
    public function beforeRun(): bool
    {
        return true;
    }

    public function afterRun(string $result): string
    {
        return $result;
    }
    //...
}
```
So you can always customize your own widgets:
```php
namespace app;

abstract class BaseWidget extends \Yiisoft\Widget\Widget
{
    // Provide any dependencies with di
    public function __construct(\Psr\EventDispatcher\EventDispatcherInterface $eventDispatcher)
    {
        $this->eventDispatcher = $eventDispatcher;
    }

    public function beforeRun(): bool
    {
        // use global events if needed
        return parent::beforeRun();
    }

    public function afterRun(string $result): string
    {
        // apply any postprocessing with or without events
        return parent::afterRun("<div class=\"widget\">$result</div>");
    }
}
```
And, of course, you can't change behavior of third party widgets.

**Comment by yiiliveext** [comment]
Why the beforeRun() and afterRun() methods have a public modfier?

**Comment by pchapl** [comment]
> Why the beforeRun() and afterRun() methods have a public modfier?

That's not a point. I think, it was just copied from yii2 as is, and may be protected.

**Comment by samdark** [comment]
@yiiliveext you're correct about that but that's not the point of the issue.

**Comment by yiiliveext** [comment]
> but that's not the point of the issue.

I never used the events in the widgets, I got nothing to say.

**Comment by cebe** [comment]
A little bit late, but: Events are a common way to extend widgets in HumHub: http://docs.humhub.org/dev-widgets.html#menus

**Comment by samdark** [comment]
@cebe that's fine. Ability to add your own events is still there.
