### ISSUE TITLE
`Widget::widget()` should accept array only as configuration

### ISSUE THREAD

**Issue by vjik** [yiisoft/widget#50]
Seems, using string or callable as configuration of widget is unnecessary.

**Comment by devanych** [comment]
> Seems, using string or callable as configuration of widget is unnecessary.

Why? It's more flexible that way. Factory also allows: https://github.com/yiisoft/factory/blob/master/src/Factory.php#L137

**Comment by vjik** [comment]
> > Seems, using string or callable as configuration of widget is unnecessary.
> 
> Why? It's more flexible that way. Factory also allows: https://github.com/yiisoft/factory/blob/master/src/Factory.php#L137

Can you give an example of using non-array configuration?

**Comment by devanych** [comment]
> Can you give an example of using non-array configuration?

This package can be used without a Yii config and container. And the container used may be specific and the `callable` will be more convenient for him.

**Comment by vjik** [comment]
> > Can you give an example of using non-array configuration?
> 
> This package can be used without a Yii config and container. And the container used may be specific and the `callable` will be more convenient for him.

This package used Yii Factory and definitions.

**Comment by samdark** [comment]
This is likely true:

1. "String" case is covered by `MyWidget::widget()` getting "MyWidget" as class name.
2. Widgets are concrete so likely there's no sense in using callable. I'm less confident in this one though.

**Comment by vjik** [comment]
Closed by #72
