### ISSUE TITLE
Make begin and end non-static

### ISSUE THREAD

**Issue by samdark** [yiisoft/widget#6]
```php
<?php $myWidget = MyWidget::widget()->begin() ?>
  test
<?= $myWidget->end() ?>
```

That would make code simpler w/o making templates syntax worse.

**Comment by terabytesoftw** [comment]
I would like it if I don't have to use a variable.

```php
<?php MyWidget::widget()->begin() ?>
    test
<?= MyWidget::end() ?>
```

**Comment by roxblnfk** [comment]
What will happen in these cases?
```php
echo $myWidget = MyWidget::widget()->begin()->begin();
echo $myWidget->end()->end();
```
```php
echo $myWidget = MyWidget::widget()->begin();
echo $myWidget;
echo $myWidget->end();
```
```php
echo $myWidget = MyWidget::widget()->begin();
echo 123;
echo $myWidget->end();
echo $myWidget->begin();
echo 456;
echo $myWidget->end();
```

**Comment by samdark** [comment]
Good examples, @roxblnfk. That would bring more harm than good.

**Comment by krissss** [comment]
> ```
> <?php $myWidget = MyWidget::widget()->begin() ?>
>   test
> <?= $myWidget->end() ?>
> ```
> 
> That would make code simpler w/o making templates syntax worse.

In Yii2, I use this to avoid exception from `MyWidget::end()`. Because:

`MyWidget` can be changed use Container DI. So after begin, widget in `$stack` is not always `MyWidget` itself. When call `MyWidget::end()` will cause exception, but `$myWidget->end()` wont.
